version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build: .
    command: poetry run python manage.py runserver 127.0.0.1:8080
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8080:8080" 
    depends_on:
      - db