# Generated by Django 5.0.1 on 2024-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about_contact_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(upload_to='workers/image'),
        ),
    ]
