# Generated by Django 5.0.1 on 2024-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('telegram', models.URLField()),
                ('you_tube', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='doi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
