# Generated by Django 5.0.6 on 2024-05-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_media',
            old_name='facebook',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='social_media',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='social_media',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='social_media',
            name='you_tube',
        ),
        migrations.AddField(
            model_name='social_media',
            name='image',
            field=models.ImageField(default=1, upload_to='thumbs/medias'),
            preserve_default=False,
        ),
    ]
