# Generated by Django 5.0.6 on 2024-05-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_facebook_social_media_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='fup_regulation',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='our_history',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='our_mission',
            new_name='phone_number',
        ),
    ]
