# Generated by Django 5.0.6 on 2024-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_redikt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redikt',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
