# Generated by Django 5.0.6 on 2024-05-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_redikt_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='redikt',
            name='work_place_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redikt',
            name='work_place_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
