# Generated by Django 5.0.6 on 2024-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_description_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='image',
            field=models.CharField(),
        ),
    ]
