# Generated by Django 5.0.6 on 2024-06-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_image_social_media_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redikt',
            name='discription',
        ),
        migrations.AddField(
            model_name='redikt',
            name='url_linkedin',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
